version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - MYSQL_ROOT_PASSWORD=YourStrong!Passw0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  mysql_data: